OFFICIAL_TOPIC_CONCEPTS: dict[str, tuple[str, ...]] = {
    "criminal_law": (
        "mens rea",
        "actus reus",
        "duress",
        "self-defence",
        "insanity defence",
        "strict liability offence",
        "entrapment",
        "attempt",
        "conspiracy",
    ),
    "contract_law": (
        "offer",
        "acceptance",
        "consideration",
        "intention to create legal relations",
        "capacity",
        "condition",
        "warranty",
        "repudiation",
        "frustration",
        "rescission",
        "specific performance",
        "liquidated damages",
        "penalty clause",
        "parol evidence rule",
        "unjust enrichment",
    ),
    "tort_law": (
        "negligence",
        "duty of care",
        "breach of duty",
        "causation",
        "remoteness of damage",
        "defamation",
        "nuisance",
        "false imprisonment",
        "trespass to land",
        "vicarious liability",
        "strict liability",
        "duty to mitigate",
    ),
    "property_law": (
        "ownership",
        "title",
        "possession",
        "leasehold",
        "freehold",
        "mortgage",
        "easement",
        "covenant",
        "adverse possession",
        "bailment",
    ),
    "constitutional_law": (
        "separation of powers",
        "judicial review",
        "due process",
        "equal protection",
        "freedom of expression",
        "rule of law",
        "proportionality",
        "legitimate aim",
        "non-discrimination",
    ),
    "administrative_law": (
        "ultra vires",
        "procedural fairness",
        "natural justice",
        "Wednesbury unreasonableness",
        "legitimate expectation",
        "delegated legislation",
        "discretionary power",
        "maladministration",
    ),
    "corporate_law": (
        "corporate personality",
        "piercing the corporate veil",
        "fiduciary duty",
        "shareholder rights",
        "director's duty of care",
        "minority protection",
    ),
    "commercial_law": (
        "force majeure",
        "arbitration clause",
        "commercial misrepresentation",
        "goods acceptance",
    ),
    "family_law": (
        "best interests of the child",
        "parental responsibility",
        "child custody",
        "consent to marriage",
        "domestic violence",
        "maintenance obligation",
        "grounds for divorce",
    ),
    "employment_law": (
        "constructive dismissal",
        "unfair dismissal",
        "non-compete clause",
        "vicarious liability (employment)",
        "redundancy",
        "discrimination",
    ),
    "civil_procedure": (
        "service of process",
        "summary judgment",
        "res judicata",
        "joinder",
        "pleading",
    ),
    "criminal_procedure": (
        "bail",
        "arraignment",
        "plea bargain",
        "double jeopardy",
    ),
    "evidence_law": (
        "burden of proof",
        "standard of proof",
        "hearsay",
        "admissibility",
        "privilege",
    ),
    "international_law": (
        "state sovereignty",
        "non-refoulement",
        "customary international law",
        "treaty interpretation",
        "jus cogens",
    ),
    "human_rights_law": (
        "freedom of religion",
        "right to privacy",
        "freedom from torture",
        "equality before law",
    ),
    "environmental_law": (
        "polluter pays principle",
        "environmental impact assessment",
        "sustainable development",
        "precautionary principle",
    ),
    "tax_law": (
        "tax avoidance",
        "tax evasion",
        "double taxation",
        "withholding tax",
    ),
    "intellectual_property_law": (
        "patent",
        "trademark",
        "copyright",
        "trade secret",
    ),
    "banking_and_finance_law": (
        "fiduciary duty (finance)",
        "secured lending",
        "capital adequacy",
        "interest rate regulation",
    ),
    "trusts_and_equity": (
        "trust",
        "constructive trust",
        "promissory estoppel",
        "unconscionability",
        "specific performance (equity)",
    ),
    "maritime_law": (
        "marine insurance",
        "bill of lading",
        "general average",
        "collision liability",
    ),
    "immigration_law": (
        "visa status",
        "deportation",
        "refugee status",
        "naturalization",
    ),
    "competition_law": (
        "price fixing",
        "abuse of dominance",
        "cartel",
        "exclusive dealing",
    ),
    "consumer_protection_law": (
        "product liability",
        "unfair contract terms",
        "cooling-off period",
        "consumer guarantees",
    ),
    "cyber_law": (
        "data protection",
        "cybercrime",
        "electronic contracts",
        "digital signature",
    ),
}


def official_topic_name(topic_key: str) -> str:
    return topic_key.replace("_", " ").title()


def official_concept_home() -> dict[str, str]:
    homes: dict[str, str] = {}
    for topic_key, concepts in OFFICIAL_TOPIC_CONCEPTS.items():
        topic_name = official_topic_name(topic_key)
        for concept_name in concepts:
            homes[concept_name.casefold()] = topic_name

    return homes
